In [1]:
import os
print(os.getcwd())
print(os.listdir())

C:\Customer_Analytics_Dashboard
['.ipynb_checkpoints', 'customer_data_analysis.ipynb', 'retail_store_sales.csv']

In [2]:
import pandas as pd

In [3]:
dataset=pd.read_csv('retail_store_sales.csv')
dataset.head(3)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False

In [4]:
dataset.shape

(12575, 11)

In [5]:
dataset.columns

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='object')

In [6]:
dataset.dtypes

Transaction ID       object
Customer ID          object
Category             object
Item                 object
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
Discount Applied     object
dtype: object

In [7]:
dataset.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [8]:
dataset.duplicated().sum()

np.int64(0)

In [9]:
dataset.nunique()

Transaction ID      12575
Customer ID            25
Category                8
Item                  200
Price Per Unit         25
Quantity               10
Total Spent           227
Payment Method          3
Location                2
Transaction Date     1114
Discount Applied        2
dtype: int64

In [10]:
dataset.describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [11]:
#we are fill this data unknow becease this data have a categorical data.
dataset['Item']=dataset['Item'].fillna('Unknow')

In [12]:
dataset["Price Per Unit"].median()

np.float64(23.0)

In [13]:
#in this column we fill median value because this data is a numerical and we are going to fill median value
dataset["Price Per Unit"]=dataset["Price Per Unit"].fillna(dataset["Price Per Unit"].median())

In [14]:
dataset["Quantity"].median()

np.float64(6.0)

In [15]:
dataset["Quantity"]=dataset["Quantity"].fillna(dataset["Quantity"].median())

In [16]:
dataset["Total Spent"].median()

np.float64(108.5)

In [17]:
dataset["Total Spent"]=dataset["Total Spent"].fillna(dataset["Price Per Unit"] * dataset["Quantity"])

In [18]:
dataset["Discount Applied"].mode()

0    True
Name: Discount Applied, dtype: object

In [19]:
dataset['Discount Applied']=dataset['Discount Applied'].fillna(dataset['Discount Applied'].mode()[0])

C:\Users\harsh\AppData\Local\Temp\ipykernel_28368\1428777080.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset['Discount Applied']=dataset['Discount Applied'].fillna(dataset['Discount Applied'].mode()[0])

In [20]:
dataset.isnull().sum()

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

In [21]:
# convert Transaction date currently it is object,but it should be a date

dataset["Transaction Date"]=pd.to_datetime(dataset["Transaction Date"],errors="coerce")

In [22]:
dataset["Transaction Date"].dtype

dtype('<M8[ns]')

In [23]:
#check whether it contain decimal values
dataset["Quantity"].unique()

array([10.,  9.,  2.,  7.,  8.,  6.,  1.,  3.,  4.,  5.])

In [24]:
dataset["Quantity"]=dataset["Quantity"].astype("Int64")

In [25]:
dataset["Quantity"]

0        10
1         9
2         2
3         9
4         7
         ..
12570     4
12571     9
12572    10
12573     6
12574     3
Name: Quantity, Length: 12575, dtype: Int64

In [26]:
#Now i will convert table name into snake name 
dataset.columns=(dataset.columns
                .str.strip()
                .str.lower()
                .str.replace(" ","_"))

In [27]:
dataset.head(3)

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2,43.0,Credit Card,Online,2022-10-05,False

In [28]:
# Check is inconsistent categories present or not
dataset["category"].unique()

array(['Patisserie', 'Milk Products', 'Butchers', 'Beverages', 'Food',
       'Furniture', 'Electric household essentials',
       'Computers and electric accessories'], dtype=object)

In [29]:
dataset["payment_method"].unique()

array(['Digital Wallet', 'Credit Card', 'Cash'], dtype=object)

In [30]:
dataset["location"].unique()

array(['Online', 'In-store'], dtype=object)

In [31]:
dataset["discount_applied"].unique()

array([ True, False])

In [32]:
#Handle impossible values
dataset[dataset["price_per_unit"]<=0]

Empty DataFrame
Columns: [transaction_id, customer_id, category, item, price_per_unit, quantity, total_spent, payment_method, location, transaction_date, discount_applied]
Index: []

In [33]:
dataset[dataset["quantity"]<=0]

Empty DataFrame
Columns: [transaction_id, customer_id, category, item, price_per_unit, quantity, total_spent, payment_method, location, transaction_date, discount_applied]
Index: []

In [34]:
dataset[dataset["total_spent"]<0]

Empty DataFrame
Columns: [transaction_id, customer_id, category, item, price_per_unit, quantity, total_spent, payment_method, location, transaction_date, discount_applied]
Index: []

In [35]:
#now we going to check outlier detection
dataset[["price_per_unit","quantity","total_spent"]].describe()

       price_per_unit  quantity   total_spent
count    12575.000000   12575.0  12575.000000
mean        23.348191  5.558648    130.208111
std         10.480413   2.79016     93.580667
min          5.000000       1.0      5.000000
25%         14.000000       3.0     52.000000
50%         23.000000       6.0    110.000000
75%         32.000000       8.0    192.000000
max         41.000000      10.0    410.000000

In [36]:
Q1=dataset["total_spent"].quantile(0.25)
Q3=dataset["total_spent"].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR
print("Lower:",lower)
print("Upper:",upper)

outlier=dataset[(dataset["total_spent"]<lower)|(dataset["total_spent"]>lower)]

Lower: -158.0
Upper: 402.0

In [37]:
outlier = dataset[
    (dataset["total_spent"] < lower) |
    (dataset["total_spent"] > upper)
]

outlier[[
    "transaction_id",
    "price_per_unit",
    "quantity",
    "total_spent"
]]

      transaction_id  price_per_unit  quantity  total_spent
27       TXN_1599706            41.0        10        410.0
133      TXN_2953434            41.0        10        410.0
339      TXN_4374445            41.0        10        410.0
869      TXN_1814138            41.0        10        410.0
1060     TXN_3710081            41.0        10        410.0
1088     TXN_1273334            41.0        10        410.0
1468     TXN_1938135            41.0        10        410.0
1505     TXN_8520397            41.0        10        410.0
1568     TXN_8048041            41.0        10        410.0
1950     TXN_1860120            41.0        10        410.0
1983     TXN_6924479            41.0        10        410.0
2153     TXN_5338814            23.0        10        410.0
2180     TXN_1172555            41.0        10        410.0
2182     TXN_4047143            41.0        10        410.0
2540     TXN_2208547            41.0        10        410.0
2658     TXN_1227978            41.0        10        410.0
3036     TXN_2624160            41.0        10        410.0
3094     TXN_7177583            41.0        10        410.0
3778     TXN_7898457            41.0        10        410.0
4526     TXN_3142066            41.0        10        410.0
4780     TXN_3465682            41.0        10        410.0
5364     TXN_8384530            41.0        10        410.0
5745     TXN_3855536            23.0        10        410.0
5756     TXN_4286472            41.0        10        410.0
5819     TXN_4456347            41.0        10        410.0
5969     TXN_2058333            41.0        10        410.0
6174     TXN_4428473            41.0        10        410.0
6374     TXN_6219786            41.0        10        410.0
6611     TXN_7056530            41.0        10        410.0
6785     TXN_6513125            41.0        10        410.0
7272     TXN_4858882            41.0        10        410.0
7372     TXN_8830035            41.0        10        410.0
7520     TXN_9553259            41.0        10        410.0
7716     TXN_9628331            41.0        10        410.0
7769     TXN_8688342            41.0        10        410.0
8076     TXN_3858239            41.0        10        410.0
8508     TXN_4771109            23.0        10        410.0
8596     TXN_2288041            23.0        10        410.0
8611     TXN_3342443            41.0        10        410.0
8845     TXN_4208189            41.0        10        410.0
8852     TXN_9745509            41.0        10        410.0
9214     TXN_2971834            41.0        10        410.0
9378     TXN_8837607            41.0        10        410.0
9620     TXN_2386101            41.0        10        410.0
9760     TXN_7254589            41.0        10        410.0
9884     TXN_8716794            41.0        10        410.0
9963     TXN_6651911            41.0        10        410.0
10103    TXN_1654267            41.0        10        410.0
10884    TXN_5286547            41.0        10        410.0
11093    TXN_5710989            41.0        10        410.0
11608    TXN_7169895            41.0        10        410.0
11610    TXN_6812555            41.0        10        410.0
11662    TXN_5870737            41.0        10        410.0
11670    TXN_9777368            41.0        10        410.0
12176    TXN_5150834            41.0        10        410.0
12189    TXN_9791556            41.0        10        410.0
12192    TXN_1657130            41.0        10        410.0
12209    TXN_1113295            41.0        10        410.0
12542    TXN_7484072            41.0        10        410.0
12557    TXN_7239201            41.0        10        410.0

In [38]:
#Total Revenue
total_revenue=dataset["total_spent"].sum()
print("Total Revenue.",total_revenue)

Total Revenue. 1637367.0

In [39]:
#Average Order value(AOV)
aov=dataset["total_spent"].sum()/dataset["transaction_id"].nunique()
print("Average Order value:",aov)

Average Order value: 130.20811133200795

In [40]:
#"Month with highest sales"
dataset["transaction_date"] = pd.to_datetime(dataset["transaction_date"])

monthly_sales = dataset.groupby(
    dataset["transaction_date"].dt.to_period("M")
)["total_spent"].sum()

print(monthly_sales)

print("Highest Sales Month:", monthly_sales.idxmax())
print("Highest Sales:", monthly_sales.max())

transaction_date
2022-01    56271.5
2022-02    46268.5
2022-03    43225.0
2022-04    42584.0
2022-05    42066.5
2022-06    44481.0
2022-07    47453.5
2022-08    43415.5
2022-09    47541.5
2022-10    40422.0
2022-11    45366.5
2022-12    41507.0
2023-01    49354.5
2023-02    41392.5
2023-03    41405.5
2023-04    41056.5
2023-05    42490.5
2023-06    44061.0
2023-07    48191.5
2023-08    40080.0
2023-09    43028.0
2023-10    40320.0
2023-11    38715.0
2023-12    45406.0
2024-01    51043.5
2024-02    40001.0
2024-03    45213.5
2024-04    48524.0
2024-05    47519.5
2024-06    47364.0
2024-07    42719.0
2024-08    46161.0
2024-09    43952.5
2024-10    45085.5
2024-11    46020.0
2024-12    50692.5
2025-01    26967.5
Freq: M, Name: total_spent, dtype: float64
Highest Sales Month: 2022-01
Highest Sales: 56271.5

In [41]:
# Category Generating the most revenue
category_revenue=dataset.groupby("category")["total_spent"].sum()
print("category_revenue")

print("Top Category:",category_revenue.idxmax())
print("Revenue:",category_revenue.max())

category_revenue
Top Category: Butchers
Revenue: 218153.0

In [42]:
#daily sales
daily_sales=dataset.groupby(dataset["transaction_date"].dt.date)["total_spent"].sum()
print(daily_sales)

transaction_date
2022-01-01    1642.5
2022-01-02    1135.5
2022-01-03     823.0
2022-01-04    1117.5
2022-01-05    2347.5
               ...
2025-01-14    1304.0
2025-01-15    1081.0
2025-01-16    1506.5
2025-01-17    1386.0
2025-01-18    1124.0
Name: total_spent, Length: 1114, dtype: float64

In [43]:
#weekly sales
weekly_sales=dataset.groupby(dataset["transaction_date"].dt.to_period("W"))["total_spent"].sum()
print(weekly_sales)

transaction_date
2021-12-27/2022-01-02     2778.0
2022-01-03/2022-01-09    10614.5
2022-01-10/2022-01-16    13319.0
2022-01-17/2022-01-23    14410.0
2022-01-24/2022-01-30    12554.5
                          ...
2024-12-16/2024-12-22     9361.5
2024-12-23/2024-12-29    12866.5
2024-12-30/2025-01-05    12650.0
2025-01-06/2025-01-12    10151.5
2025-01-13/2025-01-19     7450.0
Freq: W-SUN, Name: total_spent, Length: 160, dtype: float64

In [44]:
#Monthly sales
monthly_sales=dataset.groupby(dataset["transaction_date"].dt.to_period("M"))["total_spent"].sum()
print(monthly_sales)

transaction_date
2022-01    56271.5
2022-02    46268.5
2022-03    43225.0
2022-04    42584.0
2022-05    42066.5
2022-06    44481.0
2022-07    47453.5
2022-08    43415.5
2022-09    47541.5
2022-10    40422.0
2022-11    45366.5
2022-12    41507.0
2023-01    49354.5
2023-02    41392.5
2023-03    41405.5
2023-04    41056.5
2023-05    42490.5
2023-06    44061.0
2023-07    48191.5
2023-08    40080.0
2023-09    43028.0
2023-10    40320.0
2023-11    38715.0
2023-12    45406.0
2024-01    51043.5
2024-02    40001.0
2024-03    45213.5
2024-04    48524.0
2024-05    47519.5
2024-06    47364.0
2024-07    42719.0
2024-08    46161.0
2024-09    43952.5
2024-10    45085.5
2024-11    46020.0
2024-12    50692.5
2025-01    26967.5
Freq: M, Name: total_spent, dtype: float64

In [45]:
#Quaterly Sales
quarterly_sales=dataset.groupby(dataset["transaction_date"].dt.to_period("Q"))["total_spent"].sum()
print(quarterly_sales)

transaction_date
2022Q1    145765.0
2022Q2    129131.5
2022Q3    138410.5
2022Q4    127295.5
2023Q1    132152.5
2023Q2    127608.0
2023Q3    131299.5
2023Q4    124441.0
2024Q1    136258.0
2024Q2    143407.5
2024Q3    132832.5
2024Q4    141798.0
2025Q1     26967.5
Freq: Q-DEC, Name: total_spent, dtype: float64

In [56]:
dataset.to_csv("cleaned_ecommerce.csv",index=False)

In [57]:
dataset.shape

(12575, 11)

In [58]:
dataset.columns

Index(['transaction_id', 'customer_id', 'category', 'item', 'price_per_unit',
       'quantity', 'total_spent', 'payment_method', 'location',
       'transaction_date', 'discount_applied'],
      dtype='object')

In [59]:
import os
os.getcwd()

'C:\\Customer_Analytics_Dashboard'

In [61]:
import os
os.path.exists("cleaned_ecommerce.csv")

True